import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/store/Providers";
import { TitleImage } from "@/components";
import { SWRProvider } from "@/store/SWRProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="app-container">
          <TitleImage />
          <SWRProvider>
            <Providers>
              {children}
            </Providers>
          </SWRProvider>
        </div>
      </body>
    </html>
  );
}
